// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmcgyqaprwocvmrjeftn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tY2d5cWFwcndvY3ZtcmplZnRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDQwNzksImV4cCI6MjA2NTQ4MDA3OX0.wbCo_3Q6vTvCcZQjVzPQsEJeEYXciTB7Lzjz0zUAtQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);